### ISSUE TITLE
Is chaintip on github working right now? 

### ISSUE THREAD

**Issue by EchterAgo** [chaintip/chaintip-reddit#4]
I tried to create a tip at https://github.com/pardeike/Harmony/issues/106 but I haven't got an email or anything.

**Comment by chaintip** [comment]
No, sorry, chaintip went down for a while. Looking into what happened now. I restarted it so you should have received your tipping instructions now. Sorry about that!

**Comment by chaintip** [comment]
It's been down for a long while now, but I'm looking at getting it running smo0thly again.
